services:

  # Backend monolito original
  app:
    build:
      context: ./microservicos
    container_name: crud-springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://usuariodobanco:senha@cluster0.datgvgs.mongodb.net/nomedobanco?retryWrites=true&w=majority
    networks:
      - app-network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - app
    networks:
      - app-network

  # Microserviço de Pessoas (8082)
  pessoa-service:
    build:
      context: ./microservicos/pessoa-service
    container_name: pessoa-service
    ports:
      - "8082:8082"
    networks:
      - app-network

  # Microserviço de Cursos (8083)
  curso-service:
    build:
      context: ./microservicos/curso-service
    container_name: curso-service
    ports:
      - "8083:8083"
    networks:
      - app-network

  # Microserviço de Disciplinas (8084)
  disciplina-service:
    build:
      context: ./microservicos/disciplina-service
    container_name: disciplina-service
    ports:
      - "8084:8084"
    networks:
      - app-network

  # Microserviço de Professores (8085)
  professor-service:
    build:
      context: ./microservicos/professor-service
    container_name: professor-service
    ports:
      - "8085:8085"
    networks:
      - app-network

  # Microserviço de Turmas (8086)
  turma-service:
    build:
      context: ./microservicos/turma-service
    container_name: turma-service
    ports:
      - "8086:8086"
    depends_on:
      - curso-service
      - professor-service
    networks:
      - app-network

  # Microserviço de Matrículas (8081)
  matricula-service:
    build:
      context: ./microservicos/matricula-service
    container_name: matricula-service
    ports:
      - "8081:8081"
    environment:
      - PESSOA_SERVICE_URL=http://pessoa-service:8082
      - CURSO_SERVICE_URL=http://curso-service:8083
    depends_on:
      - pessoa-service
      - curso-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge